Updates ACK runtime to v0.14.1
aws-controllers-k8s/rds-controller pull request #34
Opened 2021-09-30 17:10 UTC by jaypipes

No other functional changes included other than runtime update.

Signed-off-by: Jay Pipes <jaypipes@gmail.com>

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

2021-09-30 17:15 UTC, RedbackThomson requested changes
Please remove the now deprecated `primary_identifier_field_name` entries:
https://github.com/aws-controllers-k8s/rds-controller/pull/34/files#diff-da5b4f2a10753269ee491b631d0505f6129d9843a5555a02430dc1428a6412e3R61-R72

2021-09-30 17:15 UTC, A-Hilaly approved these changes

2021-09-30 17:18 UTC, jaypipes commented
> Please remove the now deprecated `primary_identifier_field_name` entries: https://github.com/aws-controllers-k8s/rds-controller/pull/34/files#diff-da5b4f2a10753269ee491b631d0505f6129d9843a5555a02430dc1428a6412e3R61-R72

nice catch. done!

2021-09-30 17:22 UTC, RedbackThomson approved these changes
Great! Thank you

/lgtm

2021-09-30 17:22 UTC, RedbackThomson commented on NOTICE
> +Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
Hmm that's not the current year

2021-09-30 17:41 UTC, vijtrip2 commented
/test rds-kind-e2e

2021-10-01 10:20 UTC, A-Hilaly commented
/retest

2021-10-01 14:48 UTC, jaypipes commented
The test is failing because the my-aurora-mysql DB cluster already exists from some previous run. I need to clean up the old resources...

2021-10-04 20:05 UTC, jaypipes commented
rds-kind-e2e

2021-10-04 20:05 UTC, jaypipes commented
/rds-kind-e2e

2021-10-04 20:57 UTC, RedbackThomson commented
/test rds-kind-e2e

2021-10-04 21:12 UTC, merged