Remove DBSecurityGroup CRD from rds-controller
aws-controllers-k8s/rds-controller pull request #80
Opened 2022-05-31 22:59 UTC by brucegucode

Issue #, if available: [issue-1290](https://github.com/aws-controllers-k8s/community/issues/1290)

Description of changes:

Since now all new RDS db instances are VPC instances, there is no need to still leave CRD DBSecurityGroup open. Now RDS db instances are using VPC security group. 
(According to https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBSecurityGroup.html )

Remove DBSecurityGroup CRD from rds-controller. Also remove the db_security_group e2e test. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-06-01 17:55 UTC, brucegucode commented on generator.yaml
> +    - DBSecurityGroup
ack, will do. I'm still trying to figure out why the code generator still generate `f26iter ` which is not used and cause test failure. I will address it in next revision in this pr.

2022-06-01 19:06 UTC, jaypipes commented on generator.yaml
> +    - DBSecurityGroup
@brucegucode you will still want to ignore the DBInstance.DBSecurityGroups field path as well.

2022-06-01 21:17 UTC, RedbackThomson requested changes
Please remove the tests for this resource as well. Deleting:
- https://github.com/aws-controllers-k8s/rds-controller/blob/main/test/e2e/tests/test_db_subnet_group.py
- https://github.com/aws-controllers-k8s/rds-controller/blob/main/test/e2e/db_subnet_group.py
- https://github.com/aws-controllers-k8s/rds-controller/blob/main/test/e2e/resources/db_subnet_group_2az.yaml

Hopefully that does the trick

2022-06-02 18:57 UTC, RedbackThomson commented
Great! Glad we figured that one out.
/approve

2022-06-03 00:03 UTC, jaypipes commented
/lgtm

2022-06-03 00:04 UTC, merged