Apply RDS API updates to CRD
aws-controllers-k8s/rds-controller pull request #81
Opened 2022-06-02 22:59 UTC by jkatz

Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1311

Description of changes: This updates the API fields available to the RDS API.  This also adds support for creating Aurora Serverless v2 clusters.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-06-02 23:00 UTC, jkatz commented
/ok-to-test

2022-06-02 23:40 UTC, RedbackThomson requested changes
Most of this looks like it can be merged as-is. Just commented on the performance insights addition to DBCluster - that will need to be fixed or we'll get a repeat of a previous bug.

2022-06-03 00:27 UTC, jkatz commented on apis/v1alpha1/db_cluster.go
> +	EnablePerformanceInsights *bool `json:"enablePerformanceInsights,omitempty"`
@RedbackThomson :+1: -- this seems a bit brittle though, is there a way we can prevent the issue #77 fixed from being reintroduced?

2022-06-03 01:03 UTC, jkatz commented on apis/v1alpha1/db_cluster.go
> +	EnablePerformanceInsights *bool `json:"enablePerformanceInsights,omitempty"`
@RedbackThomson OK, I believe I got the changes from #77 in.

2022-06-03 16:10 UTC, jaypipes approved these changes
Awesome, thanks @jkatz! :)

2022-06-03 16:29 UTC, jkatz commented
/ok-to-test

2022-06-03 16:30 UTC, RedbackThomson commented
/ok-to-test

2022-06-08 01:35 UTC, jkatz commented
@RedbackThomson I've adjusted the patch so the renames for `EnablePerformanceInsights` in `DBCluster` mirror the work in `DBInstance`.

That said, I saw aws-controllers-k8s/runtime#92 and wanted to check if the renaming was still necessary. There is the open question if we want to make the boolean names be declarative, but from a technical perspective, do we need to rename thes values still?

2022-06-18 00:07 UTC, RedbackThomson commented
/lgtm

2022-06-18 00:08 UTC, merged